spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?useSSL=false
    username: root
    password: password
    
    #JPA Settings
jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect